TEST_DATA = {
    'luontokohde': (
        {'uri': 'http%3A//kulttuurisampo.fi/annotaatio%23RakennettuKohde_51-044_instance',
         'description': 'Lorem ipsum dolor sit amet.',
         'lat': 60.17,
         'lng': 24.94},
        {'uri': 'http%3A//kulttuurisampo.fi/annotaatio%23RakennettuKohde_51-044_instance',
         'description': 'Lorem ipsum dolor sit amet.',
         'lat': 60.17,
         'lng': 24.94},
        {'uri': 'http%3A//kulttuurisampo.fi/annotaatio%23RakennettuKohde_51-044_instance',
         'description': 'Lorem ipsum dolor sit amet.',
         'lat': 60.17,
         'lng': 24.94},
        {'uri': 'http%3A//kulttuurisampo.fi/annotaatio%23RakennettuKohde_51-044_instance',
         'description': 'Lorem ipsum dolor sit amet.',
         'lat': 60.17,
         'lng': 24.94},
        {'uri': 'http%3A//kulttuurisampo.fi/annotaatio%23RakennettuKohde_51-044_instance',
         'description': 'Lorem ipsum dolor sit amet.',
         'lat': 60.17,
         'lng': 24.94},
        ),
    'museo': (
        {'uri': 'http%3A//www.museot.fi/rdf/pm21151',
         'description': 'Lorem ipsum dolor sit amet.',
         'lat': 60.17,
         'lng': 24.94},
        {'uri': 'http%3A//www.museot.fi/rdf/pm21151',
         'description': 'Lorem ipsum dolor sit amet.',
         'lat': 60.17,
         'lng': 24.94},
        {'uri': 'http%3A//www.museot.fi/rdf/pm21151',
         'description': 'Lorem ipsum dolor sit amet.',
         'lat': 60.17,
         'lng': 24.94},
        {'uri': 'http%3A//www.museot.fi/rdf/pm21151',
         'description': 'Lorem ipsum dolor sit amet.',
         'lat': 60.17,
         'lng': 24.94},
        {'uri': 'http%3A//www.museot.fi/rdf/pm21151',
         'description': 'Lorem ipsum dolor sit amet.',
         'lat': 60.17,
         'lng': 24.94},
        ),
    'rakennettu': (
        {'uri': 'http%3A//kulttuurisampo.fi/annotaatio%23RakennettuKohde_51-044_instance',
         'description': 'Lorem ipsum dolor sit amet.',
         'lat': 60.17,
         'lng': 24.94},
        {'uri': 'http%3A//kulttuurisampo.fi/annotaatio%23RakennettuKohde_51-044_instance',
         'description': 'Lorem ipsum dolor sit amet.',
         'lat': 60.17,
         'lng': 24.94},
        {'uri': 'http%3A//kulttuurisampo.fi/annotaatio%23RakennettuKohde_51-044_instance',
         'description': 'Lorem ipsum dolor sit amet.',
         'lat': 60.17,
         'lng': 24.94},
        {'uri': 'http%3A//kulttuurisampo.fi/annotaatio%23RakennettuKohde_51-044_instance',
         'description': 'Lorem ipsum dolor sit amet.',
         'lat': 60.17,
         'lng': 24.94},
        {'uri': 'http%3A//kulttuurisampo.fi/annotaatio%23RakennettuKohde_51-044_instance',
         'description': 'Lorem ipsum dolor sit amet.',
         'lat': 60.17,
         'lng': 24.94},
        ),
    }
